<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Medication;

class MedicationSeeder extends Seeder
{
    public function run(): void
    {
        $names = [
            "Perfectodil 5% spray",
            "Perfectodil 2% spray",
            "Hair plus back 5% Foam",
            "Hair plus back 5% spray",
            "Hair plus back 2% spray",
            "Performa Extra strength 5% Spray",
            "Minoxidil Forte 5% Gel",
            "Momenta cream (30 gm)",
            "Elica-M cream (30 gm)",
            "Kerella lotion",
            "Kerella Ointment",
            "Diprosalic Lotion",
            "Diprosalic Ointment",
            "Elicasal Ointment",
            "Betaderm Cream",
            "Betaderm Ointment",
            "Iverzine 6 mg Tablets",
            "Iverzine 1% Cream",
            "Iverzine 1% Lotion",
            "Miconaz oral Gel",
            "Miconaz Cream",
            "Daktarin Oral gel",
            "Daktarin Cream",
            "Daktacort Cream",
            "Active hair Oil",
            "Pross Hair Lotion",
            "Vital hair Oil",
            "Pross hair Cream",
            "Ketoral plus Shampoo",
            "Nermostar Shampoo",
            "Glossy Keratin Shampoo",
            "Betadine Shampoo",
            "Sparkle Shampo ( Dry hair/  الاخضر)",
            "Final 2 Shampoo",
            "Final 2 Spray",
            "Capry Top Cream",
            "Capry Top Soap",
            "Clindasol Topical Gel",
            "Clindasol Topical solution",
            "Clindagram Gel",
            "Isoromyderm Gel",
            "Acni-Act Gel",
            "Jackodan Gel",
            "Acne Stop Cream",
            "Acne stop Soap",
            "Acne Stop Cleanser",
            "Natry Soap",
            "Synobar Soap",
            "Synobar-S Soap",
            "Hydro soap",
            "Sensoderm Soap for sensitive skin",
            "Sensoderm Moisturizing Soap",
            "Sensoderm T.S Soap",
            "Hiderm Soap",
            "Three Zed Topical Lotion",
            "Divozine Topical Lotion",
            "Girly hair Oil",
            "Pross hair Serum",
            "Herbamix Hair Oil",
            "Nizapex Shampo",
            "Seleno care Shampo",
            "Blanka Cream",
            "Blank-S cream",
            "Foldex cream",
            "Romix cream",
            "Lightvel Cream",
            "Pearla Cream",
            "Shaan Soothing gel",
            "Helarium Cream",
            "Contractubex gel",
            "Adapalene 1% Gel",
            "Marpalene 1% Cream",
            "Acretin 0.05% Cream",
            "Acretin 0.025% Cream",
            "Callomack Paint",
            "H2O2 10% Solution",
            "Potassium Permngnate 1/8000 Solution",
            "Boric acid 4% Solution",
            "Salicylic acid Soap",
            "Sulphur Soap",
            "Epicopred 5 mg Tablets",
            "Epicopred 20 mg Tablets",
            "Solupred 5 mg Tablet",
            "Solupred 20 mg Tablet",
            "Disprelone-D 5 mg tablets",
            "Disprelone-D 20 mg tablets ORODISPERSABLE",
            "Disprelone-D 20 mg tablets DISPERSABLE",
            "Colchicine 0.6 mg tablets",
            "Xilone 5mg/5ml Syrup",
            "Xilone Forte 15mg/5ml Syrup",
            "Predsol  5mg/5ml Syrup",
            "Predsol Forte 15mg/5ml Syrup",
            "Orazone 0.1mg/ml syrup",
            "Apidone syryp",
            "Phenadone syryp",
            "Letridone Oral solution",
            "Orazone 0.5mg Tablets",
            "Doxycost 200 mg Tablet",
            "Doxycost 50 mg Tablets",
            "DoxyDox 100 mg Capsules",
            "Vibramycin 100 mg Capsules",
            "Zisrocin 500 mg Capsules",
            "Xithrone 500 mg tablets",
            "Azi-once 250 mg Capsules",
            "Azrolid 500 mg Tablets",
            "Neozolid 600 mg Tablets",
            "Fungican 150 mg Capsules",
            "Itrapex 100 mg Capsules",
            "Itracon 100 mg Capsules",
            "Itranox 100 mg Capsules",
            "Nolvadex 10 mg Tablets",
            "Vitastress Tablets",
            "Hairtonic Capsules",
            "Hi Potency Formula tablets",
            "Zinctron Capsules",
            "Ferrotron Capsules",
            "Feroglobin Capsules",
            "Feroglobin Liquid syrup",
            "Iroferin Capsules",
            "Mextra Tablets",
            "Net Look 10 mg Capsules",
            "Net Look 20 mg Capsules",
            "Net Look 40 mg Capsules",
            "Isotretinoin 20 mg Capsules",
            "Isotretinoin 40 mg Capsules",
            "Duricef 500 mg Capsules",
            "Duricef 1 gm tablets",
            "Duricef 250 mg/5 ml oral suspension",
            "Duricef 500 mg/5 ml oral suspension",
            "Curisafe 500 mg capsules",
            "Curisafe 1 gm tablets",
            "Curisafe 250 mg/5 ml oral suspension",
            "Curisafe 500 mg/5 ml oral suspension",
            "Garamycin Ointment 15 gm",
            "Garamycin Cream 15 gm",
            "Farcocin Cream 20 gm",
            "Farcocin Ointment 20 gm",
            "Fusi Cream",
            "Fusiderm Cream",
            "Fucidin Cream",
            "Fito cream",
            "Mebo Ointment",
            "Bee Care Cream",
            "Hi Panthen Plus Cream",
            "Dapsocryl Gel",
            "Fipicodazoel Gel",
            "Melanofree Cream",
            "Tritospot Cream",
            "Texacort Cream",
            "Trimelasma Cream",
            "Tarolimus 0.03% ointment",
            "Treczimus 0.03% Ointment",
            "Treczimus 0.1% Ointment",
            "Elidel Cream",
            "Ruxotop 1.5% Cream",
            "Dermovate Cream",
            "Dermovate Ointment",
            "Sebanoin Gel",
            "Closol Topical Spray",
            "Ferrofol Capsules",
            "Ferrofol Vit Zinc capsules",
            "Acyclovir 800 mg tablets",
            "Lovir 800 mg tablets",
            "Zovirax 400 mg/5ml oral Suspension",
            "Lovir 400 mg tablets",
            "Acyclovir 400 mg tablet",
            "Acyclovir Cream",
            "Neurovit IM ampoles",
            "Neuroton IM ampoules",
            "Gaptin 300 mg capsules",
            "Gaptin 400 mg capsules",
            "Milga tablets",
            "Mixderm Cream",
            "Quadriderm Cream",
            "Glenosalic Ointment",
            "Cutivate Cream",
            "Betaval Cream",
            "Betaval Ointment",
            "Borgasone lotion",
            "Borgasone Cream",
            "Borgasone Ointment",
            "Trental 400mg S.R tablets",
            "Betolvex Ampoules",
            "Vita hair Tablet",
            "Aloekita D.S Shampo",
            "Aloekita Hair Mask",
            "Aloekita Leave-in Cream",
            "Elone keratin Shampoo",
            "Elone Keratin Cream",
            "Glossy hair Conditioner",
            "Tyromax cream",
            "Oil of bergamot 15% solution",
            "Oil of bergamot 20% solution",
            "Aluminum Chloride 15% solution",
            "Aluminum Chloride 20% solution",
            "Be Ready Cream",
            "Bobai Sunscreen lotion SPF45+",
            "Bobai Sunscreen Hydrocare Gel SPF50+",
            "Bobai Sunscreen Cream SPF80+",
            "Infinity Care Hydro Boost Gel SPF50+",
            "Infinity Care Sunscreen Lotion SPF50+",
            "Shaan Body Milk",
            "Shaan Lip Balm",
            "Luna Lip balm",
            "Luna Body Milk",
            "Bless Leave-in Cream Shea butter",
            "Bless Leave-in Cream Argan Oil",
            "Bless Leave-in Cream Cocunut Oil",
            "Maxanagen Hair Mask",
            "Clary Hair Mask",
            "Solumart Hair Mask for Dry & Damaged hair",
            "Elbavit syrup",
            "Elbavit with Iron syrup",
            "Sansovit plus syrup",
            "Sansovit with Iron Syrup",
            "Sansovit Syrup",
            "Zinc Origin tablet",
            "Zinkeem capsules",
            "Zinc Origin syrup",
            "Zinc Olive cream",
            "Baby Johnson oil",
            "Baby Johnson Shampo",
            "Moist-1 cream",
            "Bobai sunscreen Kids lotin SPF30+",
            "Bobai Sunscreen Hydrocare Tinted Gel SPF50+",
            "Totavit syrup",
            "Rakuten cream",
            "Promix hair spray",
            "Dandivera Hair Spray",
            "Xyclindo Foam",
            "Zyrtec syrup",
            "Azaderm Cream",
            "Zyrtec Tablets",
            "Desa Tablets",
            "Allear tablets",
            "Tryptizole 25 mg tablet",
            "Tryptizole 10 mg tablet",
            "Anallerge-4 tablet",
            "Histazin-1 tablet",
            "Levcet tablets",
            "Mosedin tablet",
            "Moodapex 50 mg tablets",
            "Claritin tablet",
            "Betafos ampoules",
            "Methabiogen 8 mg tablet",
            "Diprofos ampoules",
            "Hydrocortisone sodium succinate 100 mg vial",
            "Dexamethazone 8 mg/2ml ampoules",
            "Avil ampoules",
            "Allerban tablet",
            "Allerban Syrup",
            "Zaditen Tablet",
            "Zaditen syrup",
            "Starkoprex 5 mg tablet",
            "Starkoprex 20 mg tablet",
            "Silden 100 mg tab",
            "Silden 50 mg tablet",
            "Viavag 100 mg tablets",
            "Viavag 25 mg tablet",
            "Ectomethrin 5% lotion",
            "Ectomethrin 2.5% lotion",
            "Tadalong 5 mg tablet",
            "Perferctil tablet",
            "Nopecia 1 mg Capsules",
            "Rootage haircare cream",
            "Shaan Hand cream",
            "Urecare cream",
            "Diacalderm ointment",
            "Carbamide cream",
            "Panthenol cream 20 gm",
            "Shaan Rejuvenating cream",
            "Shoma cream",
            "Cabdicure cream",
            "Nizoderm cream",
            "Wellofung cream",
            "Lamifen cream",
            "Lamifen 250 mg tablet",
            "Lamifen 125 mg tablet",
            "Terbin 250 mg tablet",
            "Terbin 125 mg tablet",
            "Pridocaine cream",
            "Fusi-zone cream",
            "Scaromash cream",
            "Scarened Gel 15 gm",
            "Healosol spray",
            "Bivtracin spray",
            "Augmentin 1 gm tablet",
            "Augmentin 625 mg tablet",
            "Augmentin 312 mg/5ml suspension",
            "Epicephin 250 mg I.M Vial",
            "Epicephin 1 gm I.M vial",
            "Epicephin 500 mg I.M Vial",
            "Ceftriaxone 250 mg I.M Vial",
            "Ceftriaxone 1 gm I.M vial",
            "Ceftriaxone 500 mg I.M Vial",
            "Wintriaxone 250 mg I.M Vial",
            "Wintriaxone 1 gm I.M vial",
            "Wintriaxone 500 mg I.M Vial",
            "Garamycin 80 mg Ampule",
            "Garamycin 40 mg Ampule",
            "Garamycin 20 mg Ampule",
            "E-moxclav 1 gm Tablet",
            "E-moxclav 625 mg Tablet",
            "E-moxclav 312 mg Suspension",
            "E-moxclav 457 mg Suspension",
            "E-moxclav 228 mg Suspension",
            "Hibiotic 1 gm Tablet",
            "Hibiotic 625 mg Tablet",
            "Hibiotic 312 mg Suspension",
            "Hibiotic 457 mg Suspension",
            "Hibiotic 228 mg suspension",
            "Uripan 5 mg tablets",
            "Uripan X.R 10 mg tablet",
            "Uripan 0.1% syrup",
            "Cidophage 500 mg Tablet",
            "Cidopahge 1000 mg Tablet",
            "Cidophage 850 mg Tablet",
            "Ultra-medanine Paint",
            "Unitrexate 50 mg/ 2 ml vial",
            "Immulant capsules",
            "Immulant syrup",
            "Immuniphar tablet",
            "Imutrexate 2.5 mg tablet",
            "Imutrexate 5 mg tablet",
            "Imutrexate 7.5 mg tablet",
            "Imutrexate 10 mg tablet",
            "Imutrexate 15 mg tablet",
            "Azathioprine 50 mg tablet",
            "Immuran (Azathioprine) 50 mg tablet",
            "Sandimmun Neoral 50 mg capsules",
            "Sandimmun Neoral 100 mg capsules",
            "Folicap 2.5 mg capsules",
            "Folic acid 5 mg tablet",
            "Folic acid 0.5 mg (500 micron) tablet",
            "Antox tablets",
            "Carogix tablets",
            "Selenium A.C.E tablets",
            "Demark Body cream",
            "Demark Face Cream",
            "Starville Eye contour Gel",
            "Cyteal antiseptic solution",
            "Sulphur 4 gm  + Salicylic 3 gm + Castor oil 5 ml in Vaseline to 100 gm",
            "Trimelasma cream (1 tube) added/mixed to Texacort cream (1 tube)",
            "Melanofree cream (1 tube) added/mixed to Texacort cream (1 tube)",
            "Azaderm cream (1 tube) added/mixed to Garamycin cream (1 tube)",
            "Sebanoin gel (1 tube) added/mixed to Garamycin cream (1 tube)",
            "Isoromyderm gel (1 tube) added/mixed to Garamycin cream (2 tubes)",
            "Elica-M cream (1 tube) added/mixed to Garamycin cream (2 tubes)",
            "Cetal syrup ",
            "Abimol tablets",
            "Brufen 600 mg tablet ",
            "Cataflam 50 mg tablet",
            "Brufen 100 mg/5ml syrup",
            "Doliprane 1 gm tablet ",
            "Ezallin 2% Paint",
            "Ciprodiazole Tablet",
            "Tavacin 500 mg tablet",
            "Tavacin 750 tablet",
            "Flagyl 125 mg / 5 ml syrup",
            "Flagyl 500 mg Tablet",
            "Kapron 500 mg Tablet ",
            "Vitamin E 1000 mg Capsules",
            "Vitamin E 400 mg Capsules",
            "C-retard 500 mg Capsules",
            "C-retard Zinc Capsules ",
            "Davalindi 5000 IU tablets",
            "Davalindi 10000 IU tablets",
            "Limitless Ossofortin 5000 IU tablets",
            "Limitless Ossofortin 10000 IU tablets",
            "Vitayami Tablets ",
            "Darkovida Capsules",
            "Acetylcistein 600 mg Sachet",
            "B&B eye contour Cream ",
            "Care by care Cream",
            "Nail 15 solution",
            "Tobrin eye Ointment",
            "Tobradex Eye Ointment",
            "Ioprost Eye drops ",
            "Infinity Eye Contour Serum",
            "Algesal Cream",
            "Kerella solution (1 tube) dissolved in Ethyl Alcohol 70% to total volume of 100 ml spray ",
            "Dermovate Ointment (1 tube) mixed/added to Garamycin Ointment (2 tubes)",
            "Dermovate Cream (1 tube) mixed/added to Garamycin Cream (2 tubes)",
            "Dermovate Ointment (1 tube) + Salicylic acid 5 gm + Castor oil 5 ml + Liquid paraffin 10 ml in Vaseline to 120 gm ",
            "Protopic 0.1% Ointment",
            "Baritava 2 mg Tablet",
            "Baritava 4 mg Tablet",
            "Andomatoid 4 mg Tablet",
            "Andomatoid 2 mgTablet ",
            "Inderal 10 mg Tablet",
            "Indocid 100 mg rectal Supp",
            "Indocid 25 mg Capsules",
            "Colmediten 0.5 mg Tablets",
            "Colchicine 0.5 mg Tablets",
            "Vacation Sunscreen Hydrogel SPF50+",
            "Infinity Care SPF50+ Mist ",
            "Infinity Care Kids SPF45+ Lotion",
            "Infinity Care tinted Lotion SPF50+",
            "Infinity Care Kids Lotion SPF45+ ",
            "Bobai sunscreen Hydrocare tinted Gel SPF50+",
            "Octozinc capsules",
            "Sulphur 4 gm  + Salicylic 3 gm + Castor oil 5 ml + Betaderm ointment (1 tube) in Vaseline to 100 gm",
            "Cetrak syrup ",
            "Cetrak tablets",
            "Fenistil 1 mg/ml oral drops",
            "Kokast 10 mg tablets",
            "Kokast 4 mg chewable Tablets ",
            "Epicopentin 300 mg capsules",
            "Epicopentin 400 mg capsules",
            "Fucicort Cream",
            "Andoderma Extra Emollient Gel",
            "Aknapalen Gel ",
            "Zarotex 0.1% gel",
            "Salicylic acid  7 gm + Castor 5 ml in vaseline to 100 gm",
            "Salicylic acid  5 gm + Castor 5 ml in vaseline to 100 gm",
            "Hairvogine tablets ",
            "Scaro gel ",
            "Allergyl Syrup",
            "Capixy Intense Hair Spray",
            "Capixy Hair Tonic Spray",
            "Selengena anti-dandruff Shampoo",
            "Azur Baby Shampoo",
            "SuperkidsHair Shampoo",
            "Superkids Hair Tonic Spray",
            "Superkids sunscreen Lotion",
            "Superkids Detangling Spray ",
            "Solarine Sun Block Lotion SPF 36",
            "Dixivit 10000 IU Tablets",
            "Epirizine Tablets",
            "Epirizine Syrup",
            "Telfast 180 mg Tablets",
            "Fexon 180 mg Tablet ",
            "Fexon 120 mg Tablets",
            "Fexon 30 mg/ 5 ml Syrup",
            "Allerfen 180 mg Tablet",
            "Allerfen 120 mg Tablets",
            "Telfast 120 mg Tablets",
            "Telfast 30 mg/ 5 ml Tablet",
            "Propamethone Cream",
            "Alphintern tab ",
            "Diane 35 Tablet",
            "Becozyme IM Ampoules",
            "Rosita Hair Cream",
            "Vividol Hair Cream",
            "Altipro Hair Serum",
            "Seroleze Hair Serum",
            "Melatex Roll-on ",
            "Starville Roll-on",
            "Eva Foot Powder",
            "Sunsilk Shampoo ( Black)",
            "Sparkle Shampoo For Kids ",
            "Glensert Cream",
            "Butaximark Cream ",
            "Betnovate Cream ",
            "Dermatin Cream ",
            "POM Shower Gel ",
            "Cal-Mag Tablets",
            "Iso-Acnetin 10 mg Capsules",
            "Iso-Acnetin 20 mg Capsules",
            "Betadine Mouth Wash ",
            "B.B.C Spray ",
            "Oracure oral Gel",
            "Polyderm Cream",
            "Clindagram Gel ",
            "Power B complex IM Ampoules",
            "Powerecta 10 mg Orodispersable Tablets",
            "Sildava 100 mg Tablets",
            "Solu-Cortef 100 mg/ 2 ml Ampoule",
            "Cidotestone 250 mg IM Ampoules",
            "Epifasi 5000 IU Ampoules",
            "Choriomon 5000 IU Ampoules",
            "Pantogar Capsules",
            "Hairtonic Capsules"
        ];
        foreach ($names as $name) {
            Medication::firstOrCreate(['name' => $name]);
        }
    }
}
