    // ...existing code...
<?php
return [
    [
        'label' => 'الأشعة والتحاليل',
        'icon' => '🧬',
        'route' => 'radiologies.index',
        'permission' => 'view_radiologies',
        'can' => 'view_radiologies',
        'match' => ['radiologies.*'],
    ],
    [
        'label' => 'المعامل',
        'icon' => '🧪',
        'route' => 'labs.index',
        'permission' => 'view_labs',
        'can' => 'view_labs',
        'match' => ['labs.*'],
    ],
    [
        'label' => 'Dashboard',
        'icon'  => '🏠',
        'route' => 'admin.dashboard',
        'can'   => null, // لأي مستخدم داخل جروب الأدمن
        'match' => ['admin.dashboard'],
    ],
    [
        'label' => 'الأمراض المزمنة',
        'icon' => 'fa-solid fa-heart-pulse',
        'route' => 'chronic-diseases.index',
        'permission' => 'view_chronic_diseases',
        'can' => 'view_chronic_diseases',
        'match' => ['chronic-diseases.*'],
    ],
    [
        'label' => 'الأدوية',
        'icon' => '💊',
        'route' => 'medications.index',
        'permission' => 'view_medications',
        'can' => 'view_medications',
        'match' => ['medications.*'],
    ],
    [
        'label' => 'الإرشادات',
        'icon' => '💡',
        'route' => 'advices.index',
        'permission' => 'view_advices',
        'can' => 'view_advices',
        'match' => ['advices.*'],
    ],
    [
        'label' => 'الخدمات',
        'icon'  => '🛎️',
        'route' => 'services.index',
        'can'   => 'services.view',
        'match' => ['services.*'],
    ],
    [
        'label' => 'فريق العمل',
        'icon'  => '👥',
        'route' => 'admin.admins.index',
        'can'   => 'manage-admins',
        'match' => ['admin.admins.index', 'admin.admins.create', 'admin.admins.edit'],
    ],
    [
        'label' => 'Patients',
        'icon'  => '👤',
        'route' => 'patients.index',
        'can'   => 'patients.view',
        'match' => ['patients.*'],
    ],
    [
        'label' => 'Visits',
        'icon'  => '📝',
        'route' => 'visits.index',
        'can'   => 'visits.view',
        'match' => ['visits.*'],
    ],
    [
        'label' => 'الروشتات',
        'icon'  => '💊',
        'route' => 'prescriptions.index',
        'permission' => 'view_prescriptions',
        'can'   => 'view_prescriptions',
        'match' => ['prescriptions.*'],
    ],
    [
        'label' => 'Labs',
        'icon'  => '🧪',
        'route' => 'labs.index',
        'can'   => 'labs.manage',
        'match' => ['labs.*'],
    ],
    // [
    //     'label' => 'Files',
    //     'icon'  => '📎',
    //     'route' => 'files.index',
    //     'can'   => 'files.manage',
    //     'match' => ['files.*'],
    // ],
    [
        'label' => 'Settings',
        'icon'  => '⚙️',
        'route' => 'admin.settings',
        'can'   => 'admin.panel',
        'match' => ['admin.settings'],
    ],
];
