<?php
return [
    [
        'label' => 'messages.sidebar.labs',
        'icon' => '🧪',
        'route' => 'labs.index',
        'permission' => 'view_labs',
        'can' => 'view_labs',
        'match' => ['labs.*'],
    ],

    [
        'label' => 'messages.sidebar.chronic_diseases',
        'icon' => '❤️',
        'route' => 'chronic-diseases.index',
        'permission' => 'view_chronic_diseases',
        'can' => 'view_chronic_diseases',
        'match' => ['chronic-diseases.*'],
    ],
    [
        'label' => 'messages.sidebar.medications',
        'icon' => '💊',
        'route' => 'medications.index',
        'permission' => 'view_medications',
        'can' => 'view_medications',
        'match' => ['medications.*'],
    ],
    [
        'label' => 'messages.sidebar.advices',
        'icon' => '💡',
        'route' => 'advices.index',
        'permission' => 'view_advices',
        'can' => 'view_advices',
        'match' => ['advices.*'],
    ],
    [
        'label' => 'messages.sidebar.services',
        'icon'  => '🛎️',
        'route' => 'services.index',
        'can'   => 'services.view',
        'match' => ['services.*'],
    ],
    [
        'label' => 'messages.sidebar.admins',
        'icon'  => '🔑',
        'route' => 'admin.admins.index',
        'can'   => 'manage-admins',
        'match' => ['admin.admins.index', 'admin.admins.create', 'admin.admins.edit'],
    ],
    [
        'label' => 'messages.sidebar.roles',
        'icon'  => '🛡️',
        'route' => 'admin.roles.index',
        'can'   => 'manage-admins',
        'match' => ['admin.roles.index', 'admin.roles.create', 'admin.roles.edit'],
    ],
    [
        'label' => 'messages.sidebar.patients',
        'icon'  => '👤',
        'route' => 'patients.index',
        'can'   => 'patients.view',
        'match' => ['patients.*'],
    ],
    [
        'label' => 'messages.sidebar.visits',
        'icon'  => '📝',
        'route' => 'visits.index',
        'can'   => 'visits.view',
        'match' => ['visits.*'],
    ],
    [
        'label' => 'messages.sidebar.prescriptions',
        'icon'  => '📄',
        'route' => 'prescriptions.index',
        'permission' => 'view_prescriptions',
        'can'   => 'view_prescriptions',
        'match' => ['prescriptions.*'],
    ],
    [
        'label' => 'messages.sidebar.settings',
        'icon'  => '⚙️',
        'route' => 'admin.settings',
        'can'   => 'admin.panel',
        'match' => ['admin.settings'],
    ],
];
