    <?php
    // جميع الصلاحيات المستخدمة في النظام
    return [
    'patients.view',
    'visits.view',
    'view_prescriptions', 'create_prescriptions', 'update_prescriptions', 'delete_prescriptions',
    'labs.manage',
    'files.manage',
    'admin.panel',
    'manage-admins',
    'roles.manage',
    'services.view',
    'services.create',
    'services.edit',
    'services.delete',
    'patients.create',
    'patients.edit',
    'patients.delete',
    'visits.create',
    'visits.edit',
    'visits.delete',
    'chronic-diseases.view',
    'view_chronic_diseases',
    'chronic-diseases.create',
    'chronic-diseases.update',
    'chronic-diseases.delete',
    'create_chronic_diseases',
    'update_chronic_diseases',
    'delete_chronic_diseases',
    'chronic_diseases.view',
    'chronic_diseases.create',
    'chronic_diseases.update',
    'chronic_diseases.delete',
    'view_medications', 'create_medications', 'update_medications', 'delete_medications',
    'view_advices', 'create_advices', 'update_advices', 'delete_advices',
    'view_labs', 'create_labs', 'update_labs', 'delete_labs',
    'view_radiologies', 'create_radiologies', 'update_radiologies', 'delete_radiologies',
    // أضف أي صلاحية جديدة هنا عند إضافة موديول جديد
];
